### ISSUE TITLE
Debug Jar File Size Issue

### ISSUE THREAD

**Issue by JovenSoh** [AY2425S1-CS2103T-W12-2/tp#125]
Jar file is a little big, identify the issue

**Comment by tzuennn** [comment]
![telegram-cloud-photo-size-5-6154398010583401413-y](https://github.com/user-attachments/assets/3c0ac93a-13ba-4239-b9e9-68c089e9f989)
I unzipped the jar file and realised that JavaFX WebView is causing our file size to be so large. Given its size, it's also mentioned under the TP constraints that we should consider whether the benefit is worth it. To address this, we could justify its inclusion by highlighting the added benefits of using WebView to display two concurrent views of Volunteer and Event?? Not too sure if its ok tho, cus I've seen other team having multiple tabs but their jar file size remains small
