### ISSUE TITLE
Find command error prompt inaccurate

### ISSUE THREAD

**Issue by tzuennn** [AY2425S1-CS2103T-W12-2/tp#142]
![Screenshot 2024-11-04 at 12 22 08 AM](https://github.com/user-attachments/assets/1b2d978a-7086-414f-b06a-aa0f7c92cb79)
To update the error message so that it uses "contains" instead of "prefix"

**Comment by tzuennn** [comment]
![Screenshot 2024-11-07 at 2 25 14 PM](https://github.com/user-attachments/assets/60301c8e-8041-4a14-b9e2-a34b5ae2c31a)
![Screenshot 2024-11-07 at 2 25 22 PM](https://github.com/user-attachments/assets/155429b5-7538-4a1c-9a39-fdd978f17edd)

**Comment by Fluffykan** [comment]
Closed by #157
