### ISSUE TITLE
Inaccurate Parameter Description

### ISSUE THREAD

**Issue by JovenSoh** [AY2425S1-CS2103T-W12-2/tp#151]
Parameter description suggests that it takes in a prefix, while any part of the string should work.

<img width="604" alt="image" src="https://github.com/user-attachments/assets/4a3c8bd6-6cea-416c-8f43-18c2279a99d0">

Similar to #142, the event says 'starting' but it does not actually start with it.

<img width="352" alt="image" src="https://github.com/user-attachments/assets/2a842a32-be85-44a0-ae3e-5d32ece273fb">

**Comment by Fluffykan** [comment]
Closed by #157
