### ISSUE TITLE
UG new volunteer sample command error

### ISSUE THREAD

**Issue by Fluffykan** [AY2425S1-CS2103T-W12-2/tp#152]
Volunteer now no longer has a time field, but it is still reflected in the UG
![image](https://github.com/user-attachments/assets/49d35533-4646-42f4-96e2-e00a6f9f6769)
![image](https://github.com/user-attachments/assets/8e6280f4-6fb7-43d7-a3e9-e017f72711b4)

**Comment by tzuennn** [comment]
PR #147 updated this

**Comment by Fluffykan** [comment]
Alright thanks @tzuennn!
