### ISSUE TITLE
Update UG Based on Review

### ISSUE THREAD

**Issue by JovenSoh** [AY2425S1-CS2103T-W12-2/tp#187]
### User Guide Improvement Checklist

- [x] **Change `locate` to `find`**  
  Update all instances of `locate` in the User Guide to `find` for consistency and clarity.

- [x] **Improve navigability to the Table of Contents**  
  - Add links to each section in the Table of Contents for easy navigation.  
  - Ensure clear headers for each section.

- [x] **Include a tip to use `list` after `find`**  
  Add a tip to recommend users run the `list` command after using `find` to review all available data.

- [x] **Make it clear for users to not touch data file**
  Can use a red warning box
@Fluffykan 

- [x] **Add constraints for the commands that have restriction**
@tzuennn 
- [x] **Provide handholding in the Table of Contents**  
  - For each command in the Table of Contents, provide a short format example (e.g., "Here is the format for `find`: `find n/NAME`").
@Fluffykan 

- [x] **Add VolunSync description to the User Guide**  
  - Include a brief introduction to VolunSync at the start of the User Guide, explaining its purpose and benefits for nonprofits.

- [x] **Help users check if they have Java 17 installed**  
  - Provide step-by-step instructions to check for Java 17 or above on their system.  
  - Include links to download Java if it's not installed.

- [x] **Add more details to `help` command**  
  - Explain that the `help` command opens the User Guide in the browser.  
  - Emphasize that the User Guide is always accessible from the `help` command.
 @Fluffykan 

- [x] **Explain the `export` command**  
  - Clearly state why a user might want to use the `export` feature (e.g., printing records, transferring data to another system).  
  - Mention the limitations, such as the lack of an import function.

- [x] **Ensure examples are consistent**  
  - Verify that all command examples follow the same format and use consistent names, emails, and other parameters.
  - @ttzuche 
 
- [x] **Make UG less AB3**  
  - Use more informal language
  - Make it feel different from the AB3 UG

- [x] **Add in new filter command**  
  - Add in how to use the `filter` command
  - @keerthigkaarthik

**Comment by keerthigkaarthik** [comment]
Closed by #198
