### ISSUE TITLE
[PE-D][Tester A] Phone number validation prevents phone numbers with country code from being added

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W12-2/tp#211]
Phone numbers should only contain numbers, and it should be 3 to 15 digits long prevents +44 020 7946 0958, a valid phone number in the UK from being added.

This limits the usability of the application across countries.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: FriedCabbageSalad/ped#2

**Comment by Fluffykan** [comment]
Thank you for raising this issue, we have taken note and included it in the planned improvements.
