### ISSUE TITLE
[PE-D][Tester B] Allows user to enter a date in the past

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W12-2/tp#213]
![image.png](https://raw.githubusercontent.com/VedJoshi/ped/main/files/e12d7465-775e-4b74-9f95-acb0568d77fc.png)

Able to add a date in the past, does not make sense and should be validated to prevent entry. 

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: VedJoshi/ped#5

**Comment by JovenSoh** [comment]
Ability to track past events so when adding a backlog of events for archiving, for example using proposed feature `import`, there would not be an error.

<img width="798" alt="image" src="https://github.com/user-attachments/assets/88243ec9-612a-4739-9d5e-62da303f8d2c">
