### ISSUE TITLE
[PE-D][Tester B] Find command can be hard to use due to name formatting

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W12-2/tp#214]
Since the spaces are preserved in the names, finding a person with an extra few spaces, maybe introduced via user error e.g `John         Doe`, cannot be found using the find command unless the exact number of spaces are known and input into the command.

![image.png](https://raw.githubusercontent.com/VedJoshi/ped/main/files/8658a343-ae93-4423-91a5-8e855c49f174.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: VedJoshi/ped#6

**Comment by JovenSoh** [comment]
`find` command does not require a complete match to work, so `/v find John ` should still work. Would keep in consideration for future improvements.

<img width="349" alt="image" src="https://github.com/user-attachments/assets/e21432f8-fd9d-4eff-9531-865df496e611">
