### ISSUE TITLE
[PE-D][Tester B] Incorrect error thrown (?)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W12-2/tp#216]
![image.png](https://raw.githubusercontent.com/VedJoshi/ped/main/files/90db7e33-fc37-4077-899d-f2aa24a25ca0.png)

Technically the error thrown is incorrect as it is the same time, very minor.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: VedJoshi/ped#7

**Comment by keerthigkaarthik** [comment]
Thanks for highlighting. We have now fixed the issue.
