### ISSUE TITLE
[PE-D][Tester C] Error message from adding events command can be misleading

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W12-2/tp#218]
![image.png](https://raw.githubusercontent.com/bryanckh/ped/main/files/17567c43-f377-4456-a93f-d50c967d9b42.png)

The error message says that the start time is after the end time, even though they are the same time. Although it's nice that you caught the bug

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: bryanckh/ped#3

**Comment by keerthigkaarthik** [comment]
Thanks for highlighting. We have now resolved the issue.
