### ISSUE TITLE
[PE-D][Tester E] Unassign is unintuitive to do if volunteers have long name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W12-2/tp#221]
The logic to unassign is to locate the volunteer's exact name in the volunteers' list to find the corresponding index, but in this scenario, it is impossible to find the index because the names are not fully shown in the volunteers' list UI.

![image.png](https://raw.githubusercontent.com/muller317/ped/main/files/5015989f-3b43-4cf1-91ab-1b8287253220.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: muller317/ped#7

**Comment by Fluffykan** [comment]
name of 100 characters is able to be displayed when VolunSync is set to fullscreen, as seen below 

![image](https://github.com/user-attachments/assets/5946b3da-5eb5-4138-b32d-22b8ad5bed2a)

following the guidelines on the course website, this is not a bug. 

![image](https://github.com/user-attachments/assets/74d37aed-0c4f-4241-8b62-5b792bc7e23b)

Furthermore, as names are limited to 100 chars in length, all names should be able to be displayed in fullscreen.
