### ISSUE TITLE
[PE-D][Tester C] Finding for events does not find accurately for multiple keywords

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W12-2/tp#223]
![image.png](https://raw.githubusercontent.com/bryanckh/ped/main/files/095c2b32-3e2c-4fc3-b38d-2a15de2c0f61.png)

The finding does not work when I find for 'don' and 'drive' together, although the expected is to find the donation drives

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: bryanckh/ped#5

**Comment by JovenSoh** [comment]
Duplicate Issue #210
