### ISSUE TITLE
[PE-D][Tester A] Assign unexpected error message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W12-2/tp#236]
All indexes are positive
![image.png](https://raw.githubusercontent.com/FriedCabbageSalad/ped/main/files/5988242a-f6c5-460c-9d29-3b38a6dcc892.png)

Expected error message

![image.png](https://raw.githubusercontent.com/FriedCabbageSalad/ped/main/files/122d3b61-496b-408b-acea-df43c3195aab.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: FriedCabbageSalad/ped#8

**Comment by keerthigkaarthik** [comment]
Thanks for highlighting. We have now highlighted the issue in our documentation.
