### ISSUE TITLE
[PE-D][Tester A] Volunteer Unfree invalid command format error message does not include all parameters

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W12-2/tp#242]
![image.png](https://raw.githubusercontent.com/FriedCabbageSalad/ped/main/files/1664e322-a1f1-4d86-87db-56e4da390b36.png)

Error message is missing the index parameter

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: FriedCabbageSalad/ped#11

**Comment by keerthigkaarthik** [comment]
Thanks for highlighting. We have now resolved the issue.
