### ISSUE TITLE
[PE-D][Tester A] Use Case: Assign volunteer to event

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W12-2/tp#266]
![image.png](https://raw.githubusercontent.com/FriedCabbageSalad/ped/main/files/32519464-db29-420c-8ebc-9924491261d8.png)

This extension does not occur in the app

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: FriedCabbageSalad/ped#20

**Comment by keerthigkaarthik** [comment]
Thanks for highlighting. We have now resolved the issue.
