### ISSUE TITLE
[PE-D][Tester A] Grammar error in DG under Launch

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W12-2/tp#270]
![image.png](https://raw.githubusercontent.com/FriedCabbageSalad/ped/main/files/b9ce897a-5b4c-408a-b1b9-94f1382d46b4.png)

Should be "The window size may not be optimal"

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: FriedCabbageSalad/ped#24

**Comment by keerthigkaarthik** [comment]
Thanks for highlighting. We have now resolved the issue.
