### ISSUE TITLE
[PE-D][Tester A] Link in DG sends you to localhost

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W12-2/tp#271]
![image.png](https://raw.githubusercontent.com/FriedCabbageSalad/ped/main/files/934fe78c-0358-4dbf-b450-24cb8845abce.png)

This link links to localhost rather than the online setting up page

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: FriedCabbageSalad/ped#25

**Comment by keerthigkaarthik** [comment]
Thanks for highlighting. We have now fixed the issue.
