### ISSUE TITLE
tP violates a constraint

### ISSUE THREAD

**Issue by damithc** [AY2425S1-CS2103T-W12-2/tp#272]
Team W12-2, 
Your jar file exceeds the max jar size we have prescribed (see https://nus-cs2103-ay2425s1.github.io/website/admin/tp-constraints.html#constraint-file-size). 

What's the reason for this large jar size? Is it just so that the help link can be opened in a browser?

**Comment by Fluffykan** [comment]
We realised it was due to the java-web dependency that was included in previous iterations and not used. We have removed it and verified that the jar file is within the size limit. Currently it is at 11.9MB

**Comment by damithc** [comment]
Nice 👍
